apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pixel-voice.fullname" . }}-config
  labels:
    {{ include "pixel-voice.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.appConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_HOST: {{ .Release.Name }}-postgresql
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ .Release.Name }}-redis-master
  {{- end }}
